// Philippine aerodrome ICAO codes, per PAGASA's aviation ICAO code list
// (https://www.pagasa.dost.gov.ph/aviation/icao-codes). The catch-all
// codes RPXX (civilian, no ICAO code) and RPZZ (military, no ICAO code)
// are intentionally excluded — filers use ZZZZ and specify the location
// in Other Information instead.
export const PHILIPPINE_AERODROMES = [
  { code: "RPLA", name: "Pinamalayan Airport" },
  { code: "RPLB", name: "Subic Bay International Airport" },
  { code: "RPLC", name: "Clark International Airport/Clark Air Base" },
  { code: "RPLG", name: "Wasig Airport" },
  { code: "RPLI", name: "Laoag International Airport" },
  { code: "RPLJ", name: "Jomalig Airport" },
  { code: "RPLL", name: "Ninoy Aquino International Airport" },
  { code: "RPLN", name: "Palanan Airport" },
  { code: "RPLO", name: "Cuyo Airport" },
  { code: "RPLP", name: "Legazpi Airport" },
  { code: "RPLQ", name: "Crow Valley Gunnery Range" },
  { code: "RPLR", name: "Rosales Airport" },
  { code: "RPLS", name: "Atienza Air Base" },
  { code: "RPLT", name: "Itbayat Airport" },
  { code: "RPLU", name: "Lubang Airport" },
  { code: "RPLV", name: "Fort Magsaysay Airfield" },
  { code: "RPLX", name: "Kindley Landing Field" },
  { code: "RPLY", name: "Alabat Airport" },
  { code: "RPLZ", name: "Sorsogon Airport" },
  { code: "RPMA", name: "Allah Valley Airport" },
  { code: "RPMB", name: "Rajah Buayan Air Base" },
  { code: "RPMC", name: "Awang Airport" },
  { code: "RPMD", name: "Francisco Bangoy International Airport" },
  { code: "RPME", name: "Bancasi Airport" },
  { code: "RPMF", name: "Bislig Airport" },
  { code: "RPMG", name: "Dipolog Airport" },
  { code: "RPMH", name: "Camiguin Airport" },
  { code: "RPMI", name: "Maria Cristina Airport" },
  { code: "RPMJ", name: "Jolo Airport" },
  { code: "RPMK", name: "Tacurong Airport" },
  { code: "RPML", name: "Lumbia Airport" },
  { code: "RPMM", name: "Malabang Airport" },
  { code: "RPMN", name: "Sanga-Sanga Airport" },
  { code: "RPMO", name: "Labo Airport" },
  { code: "RPMP", name: "Pagadian Airport" },
  { code: "RPMQ", name: "Imelda R. Marcos Airport" },
  { code: "RPMR", name: "General Santos International Airport" },
  { code: "RPMS", name: "Surigao Airport" },
  { code: "RPMT", name: "Del Monte Plantation Airstrip" },
  { code: "RPMU", name: "Cagayan de Tawi-Tawi Airport" },
  { code: "RPMV", name: "Ipil Airport" },
  { code: "RPMW", name: "Tandag Airport" },
  { code: "RPMX", name: "Liloy Airport" },
  { code: "RPMY", name: "Malaybalay Airport" },
  { code: "RPMZ", name: "Zamboanga International Airport" },
  { code: "RPNO", name: "Siocon Airport" },
  { code: "RPNS", name: "Sayak Airport" },
  { code: "RPSB", name: "Bantayan Airport" },
  { code: "RPSD", name: "Taytay-Sandoval Airport" },
  { code: "RPSG", name: "Sicogon Airport" },
  { code: "RPSM", name: "Panan-awan Airport" },
  { code: "RPSN", name: "Ubay Airport" },
  { code: "RPSR", name: "Semirara Airport" },
  { code: "RPTP", name: "Tarumpitao Point Airport" },
  { code: "RPUA", name: "Aparri Airport" },
  { code: "RPUB", name: "Loakan Airport" },
  { code: "RPUC", name: "Cabanatuan Airport" },
  { code: "RPUD", name: "Bagasbas Airport" },
  { code: "RPUE", name: "Lucena Airport" },
  { code: "RPUF", name: "Basa Air Base" },
  { code: "RPUG", name: "Lingayen Airport" },
  { code: "RPUH", name: "San Jose Airport" },
  { code: "RPUI", name: "Iba Airport" },
  { code: "RPUJ", name: "Castillejos Airfield" },
  { code: "RPUK", name: "Calapan Airport" },
  { code: "RPUL", name: "Fernando Air Base" },
  { code: "RPUM", name: "Mamburao Airport" },
  { code: "RPUN", name: "Naga Airport" },
  { code: "RPUO", name: "Basco Airport" },
  { code: "RPUP", name: "Jose Panganiban Airport" },
  { code: "RPUQ", name: "Mindoro Airport" },
  { code: "RPUR", name: "Baler Airport" },
  { code: "RPUS", name: "San Fernando Airport" },
  { code: "RPUT", name: "Tuguegarao Airport" },
  { code: "RPUU", name: "Bulan Airport" },
  { code: "RPUV", name: "Virac Airport" },
  { code: "RPUW", name: "Marinduque Airport" },
  { code: "RPUX", name: "Plaridel Airport" },
  { code: "RPUY", name: "Cauayan Airport" },
  { code: "RPUZ", name: "Bagabag Airport" },
  { code: "RPVA", name: "Daniel Z. Romualdez Airport" },
  { code: "RPVB", name: "New Bacolod-Silay Airport" },
  { code: "RPVC", name: "Calbayog Airport" },
  { code: "RPVD", name: "Sibulan Airport" },
  { code: "RPVE", name: "Godofredo P. Ramos Airport" },
  { code: "RPVF", name: "Catarman National Airport" },
  { code: "RPVG", name: "Guiuan Airport" },
  { code: "RPVH", name: "Hilongos Airport" },
  { code: "RPVI", name: "Iloilo Airport" },
  { code: "RPVJ", name: "Masbate Airport" },
  { code: "RPVK", name: "Kalibo Airport" },
  { code: "RPVL", name: "Roxas-del Pilar Airport" },
  { code: "RPVM", name: "Mactan-Cebu International Airport" },
  { code: "RPVN", name: "Medellin Airport" },
  { code: "RPVO", name: "Ormoc Airport" },
  { code: "RPVP", name: "Puerto Princesa International Airport" },
  { code: "RPVQ", name: "Biliran Airport" },
  { code: "RPVR", name: "Roxas Airport" },
  { code: "RPVS", name: "Evelio Javier Airport" },
  { code: "RPVT", name: "Tagbilaran Airport" },
  { code: "RPVU", name: "Tugdan Airport" },
  { code: "RPVV", name: "Francisco Reyes Airport" },
  { code: "RPVW", name: "Borongan Airport" },
  { code: "RPVX", name: "Dolores Airport" },
  { code: "RPVY", name: "Catbalogan Airport" },
  { code: "RPVZ", name: "Siquijor Airport" },
] as const;

const AERODROME_NAMES_BY_CODE = new Map<string, string>(
  PHILIPPINE_AERODROMES.map((aerodrome) => [aerodrome.code, aerodrome.name]),
);

export function getAerodromeName(code: string): string | null {
  return AERODROME_NAMES_BY_CODE.get(code.toUpperCase()) ?? null;
}
