-- Human-friendly unique identifier for flight plans: FP-YYMMDD-XXXX
-- (filing date + 4 digits). Generated by the create action; existing rows
-- are backfilled deterministically from their id so the backfill cannot
-- collide.

alter table public.flight_plans
  add column plan_code text;

update public.flight_plans
set plan_code =
  'FP-' || to_char(created_at, 'YYMMDD') || '-' ||
  upper(left(replace(id::text, '-', ''), 4))
where plan_code is null;

alter table public.flight_plans
  alter column plan_code set not null;

alter table public.flight_plans
  add constraint flight_plans_plan_code_key unique (plan_code);
